### ISSUE TITLE
Issue in getYear and project link

### ISSUE THREAD

**Issue by jessejay356** [sparkfun/SparkFun_RV-8803_Arduino_Library#1]
1) The link in the source is to the wrong location, it leads to a 404

2) Get year is wrong in the latest version.

It's currently

uint16_t RV8803::getYear() {
   return BCDtoDEC(_time[TIME_YEAR] + 2000); 
}

The issue is it's doing BCDtoDEC on the value AFTER adding 2000, and it should be after the BCDtoDEC call when that should happen... like the following.

uint16_t RV8803::getYear() {
   return(BCDtoDEC(_time[TIME_YEAR]) + 2000); 
}

**Comment by adamgarbo** [comment]
Hi @jessejay356, 

Good catch. I created a PR to address these issues. Once Andy merges my branch, this issue can be closed.

Cheers,
Adam

**Comment by zjwhitehead** [comment]
Cool looks like this can be closed now

**Comment by AndyEngland521** [comment]
Woops, correct, fixed in v1.0.3
