### ISSUE TITLE
setHundredthsToZero return type should be void

### ISSUE THREAD

**Issue by vinthewrench** [sparkfun/SparkFun_RV-8803_Arduino_Library#10]
the code for 

bool RV8803::setHundredthsToZero()
{
	writeBit(RV8803_CONTROL, CONTROL_RESET, ENABLE);
	writeBit(RV8803_CONTROL, CONTROL_RESET, DISABLE);
}

SparkFun_RV8803.cpp: In member function 'bool RV8803::setHundredthsToZero()':
SparkFun_RV8803.cpp:260:1: warning: no return statement in function returning non-void [-Wreturn-type]
 
 please change it to void or return something

**Comment by AndyEngland521** [comment]
Great catch, this would likely cause problems on Artemis if I remember correctly. Fixed in v1.1.1 by returning the status of both writeBit operations ANDed together. (If either fails, the function should return 0)
