### ISSUE TITLE
readRegister - control reaches end of non-void function

### ISSUE THREAD

**Issue by vinthewrench** [sparkfun/SparkFun_RV-8803_Arduino_Library#11]
the code for 

uint8_t RV8803::readRegister(uint8_t addr)
{
	_i2cPort->beginTransmission(RV8803_ADDR);
	_i2cPort->write(addr);
	_i2cPort->endTransmission();

    //typecasting the 1 parameter in requestFrom so that the compiler
    //doesn't give us a warning about multiple candidates
    if (_i2cPort->requestFrom(static_cast<uint8_t>(RV8803_ADDR), static_cast<uint8_t>(1)) != 0)
    {
        return _i2cPort->read();
    }
}

could fail and return unpredictable value.

**Comment by AndyEngland521** [comment]
Great catch, fixed in v1.1.1 to return false by default.
