### ISSUE TITLE
Rename ENABLE/DISABLE definitions

### ISSUE THREAD

**Issue by adamgarbo** [sparkfun/SparkFun_RV-8803_Arduino_Library#16]
Hey @AndyEngland521,

Another quick suggestion to rename the following two definitions to something a little more specific to the RV-8803 library:

https://github.com/sparkfun/SparkFun_RV-8803_Arduino_Library/blob/f5935afc03aa94336144f708f9c3e17db3d37935/src/SparkFun_RV8803.h#L124-L125

ENABLE and DISABLE are commonly used, and I've already run into some conflicts with duplicate definitions in the SAMD21 core.

Cheers,
Adam

**Comment by nseidle** [comment]
Fixed
