### ISSUE TITLE
Making "use1970sEpoch" default to true breaks backwards compatibility.

### ISSUE THREAD

**Issue by gtjoseph** [sparkfun/SparkFun_RV-8803_Arduino_Library#23]
I just killed a sunday morning trying to figure out why my rtc code no longer works.  Turns out, adding "use1970sEpoch" to setEpoch() and making the default true automatically subtracts 946710000 from the value provided to the function and causes a time warp back to 1951.  You should probably make that default to false to preserve existing behavior.

Oh, ESP32.

**Comment by nseidle** [comment]
My apologies @gtjoseph. It's always my best laid plans that blow up in your face. Should be fixed in v1.2.1.

**Comment by gtjoseph** [comment]
> It's always my best laid plans that blow up in your face

Don't I know it. :)
Thanks!
