### ISSUE TITLE
How can reset the RTC?

### ISSUE THREAD

**Issue by ionel-dragomirescu** [sparkfun/SparkFun_RV-8803_Arduino_Library#26]
Hi,
I have the following issue:
On the same I2C bus is connected RV-8803 and I2C LiquidCristal from DFROBOT (DFR0063 - https://www.dfrobot.com/product-135.html)
The RV-8803 is always power using 3V lithium battery.

Some time, the RV-8803 stop the work. Time his no updated. If I try to get time, the driver report always same date / time. Even IRQ stop to work.
I think the RTC stay in a state where nothing is happend.

How can I get out from this state?

Thank you,
Ionel

**Comment by nseidle** [comment]
Does the device work normally when the DFR0063 is disconnected from the bus?

What happens when you run the examples in this library?

**Comment by RWBRWB** [comment]
If you may be seeing low power conditions the RTC may be triggering the RESET bit to 1 which freezes time. 

The function below will set the RESET bit back to 0 and time will keep counting as normal. 

I have a bunch of stuff on a breadboard wired up and a amp powering speakers so a few as of power which would cause some voltage sag which would cause the RTC to freeze up and set that RESET bit to 1. Only removing the coin cell would reset the RESET Bit to 0 allowing the time to work again. 

Took me a few years to figure this out LOL

rtc.writeBit(RV8803_CONTROL, CONTROL_RESET, RV8803_DISABLE); //Set RESET bit to 0 after setting time to make sure seconds don't get stuck.

**Comment by ionel-dragomirescu** [comment]
Hi,

First, thank for the answers.

[nseidle](https://github.com/nseidle), the RTC device work fine when DFR0063 is disconnected from the I2C bus.
[RWBRWB](https://github.com/RWBRWB) You also I think have right, most probably it's a power problem. 
Still I ave a lipo battery (coin cell ) for power RTC device as a backup and in my opinion this think should not it happens.
I do not understood why it happens ? :)

Instead rtc.writeBit(RV8803_CONTROL, CONTROL_RESET, RV8803_DISABLE) I use 
rtc.setHundredthsToZero() which I think it's the same an seems to work.

Thank you again,
BR,
Ionel

**Comment by nseidle** [comment]
@RWBRWB - Thanks for the reported fix and helping out!

@ionel-dragomirescu - Sounds like a power glitch or surge on your bus that may be causing the RTC to freeze. Please use RWBRWB's suggested solution and let us know if it works or fails. I'll close this issue since it sounds like you're working.
