### ISSUE TITLE
Seconds do not increment after setting time sometimes > Solution

### ISSUE THREAD

**Issue by RWBRWB** [sparkfun/SparkFun_RV-8803_Arduino_Library#27]
I have been testing the RV-8803 for a awhile now and sometimes the time would get messed up and need to be reset. 

After I reset the time the seconds would not increment but would stick at whatever they were set at. 

The only way to fix this was to cut the power + pull the coin cell and put it back in to power cycle the RV-8803. 

I found the reason this was happening today. 

I think a Low Voltage event would trigger the time to get messed up. This set the RESET bit high in the x0F control register which prevents the seconds from ticking when resetting the hundredths timer. 

Because the SetTime() function does not clear the RESET bit in the Control Register it will not allow the seconds to run. 

To fix this we simply need to add this code after setting the time to make sure the RESET bit in the 0x0F Control Register is set to 0. 

`rtc.writeBit(RV8803_CONTROL, CONTROL_RESET, RV8803_DISABLE); //Set RESET bit to 0 after setting time to make sure seconds don't get stuck.`

Now I don't have to pull the coin cell from the circuit anymore ;-)

**Comment by nseidle** [comment]
Thanks @RWBRWB! Do you recommend we implement your writeBit() 'fix' into the SetTime function? It sounds like the RTC freeze is a rare case.

**Comment by RWBRWB** [comment]
Yea I would add the command to set the time function since there is no negative side effects by resetting the RESET bit when setting the time. 

You have to pull the RTC battery to get the RESET bit to go back to 0 otherwise which would be a real pain if this happened on a end use product where the battery is not easily reachable or worse soldered to the PCB. 

I came across other's experiencing this same time stuck issue after setting time on older Arduino Forum threads so it's happening to others also it seems. 

Have to remember these RTC breakouts are being used on breadboards first which increases the likelihood of less than ideal power supply wiring. I think this RTC is more prone to glitching out than some other IC's from my experience. 

Just my 2 Cents :-)

**Comment by nseidle** [comment]
Added. Everything works for me but I can't replicate the original glitch. Can you please give the new code a try? I haven't done a release so the new version won't be available via Arduino lib manager (you'll have to pull the repo).

**Comment by RWBRWB** [comment]
Hey Nathan, 

Happy to see that you added the fix. 

If you mess with the I2C lines, mainly remove pull up voltage or similar the time register will usually max out and return maxed out readings. I came across many getting into this situation on different form post so it happens. 

After that happens if you try to reset the time without the fix it will reset but the second count will stick at 00 and the time will not progress past what you set it to be. Without the fix added you have to pull the RTC  battery to reset the RTC chip and then program the time again for it to work correctly again after setting the time. 

With the fix added you can simply set the time again and everything starts working again like a Swiss watch :-)

**Comment by nseidle** [comment]
Awesome, thanks!
