### ISSUE TITLE
"with +/-3ppm per year of deviation"

### ISSUE THREAD

**Issue by beta-tester** [sparkfun/SparkFun_RV-8803_Arduino_Library#33]
> with +/-3ppm per year of deviation

what does it mean?

i thought ppm is parts per million and means that in 1000000s the deviation is within &PlusMinus;3s.

1000000s = 11,5740740741days so 3ppm are &PlusMinus;3 seconds in ~12days or 1 second in ~4days.
0,2592 seconds per day,
94.608 seconds per year.
but why mention &PlusMinus;3ppm per year? is a year not an unusual unit for a RTC?

**Comment by PaulZC** [comment]
Hi,

This comes from the datasheet:

![image](https://github.com/sparkfun/SparkFun_RV-8803_Arduino_Library/assets/5690545/965994f6-3383-412f-bfea-fe1e703cdddc)

I take it to mean that the internal crystal will change by no more than 3ppm during its first year - at constant temperature.

Best wishes,
Paul

**Comment by beta-tester** [comment]
sorry... my fault.
:blame

**Comment by PaulZC** [comment]
No worries!

**Comment by beta-tester** [comment]
> with +/-3ppm per year of deviation

but then it is still not correct,
it is not &PlusMinus;3ppm **per** year
it is aging &PlusMinus;3ppm **in the first** year.
in the second year it can be bigger than &PlusMinus;3ppm

**Comment by adamgarbo** [comment]
> in the second year it can be bigger than ±3ppm

Maximum deviation of 3 ppm in the first year (aging), and then 3 ppm per year (between -40 to 85°C) afterwards for the life of the crystal.

I suggest researching the topic. There is plenty of information online explaining RTC deviation in more detail. 

Here's a fun calculator you can use:
https://www.analog.com/en/design-center/interactive-design-tools/real-time-clock-calculator.html
