### ISSUE TITLE
Example4B-Countdown_Interrupt

### ISSUE THREAD

**Issue by ionel-dragomirescu** [sparkfun/SparkFun_RV-8803_Arduino_Library#5]
I have tried to use the example Example4B-Countdown_Interrupt and change the statement:
rtc.setCountdownTimerFrequency(COUNTDOWN_TIMER_FREQUENCY_64_HZ);
rtc.setCountdownTimerClockTicks(224);

with:

rtc.setCountdownTimerFrequency(COUNTDOWN_TIMER_FREQUENCY_1_HZ);
rtc.setCountdownTimerClockTicks(5);

The interrupt is not generated. 

The following constant: COUNTDOWN_TIMER_FREQUENCY_1/60_HZ does not work either.

Is this a known issue?

Thank you,

**Comment by AndyEngland521** [comment]
This is not a known issue, I'll investigate a bit further. have you tried using either of the corresponding get functions to attempt to retrieve the values in those registers?

**Comment by ionel-dragomirescu** [comment]
Yes I retrieve values from registers and values are set correct.

**Comment by ionel-dragomirescu** [comment]
I read the RV8803 specs and have a look to the library and find the following statement which work:

  rtc.disableAllInterrupts();
  rtc.setCountdownTimerEnable(DISABLE);             // TE = 0
  rtc.disableHardwareInterrupt(TIMER_INTERRUPT);    // TIE = 1
  rtc.clearInterruptFlag(FLAG_TIMER);               // TF = 0
  rtc.setCountdownTimerFrequency(COUNTDOWN_TIMER_FREQUENCY_1_60_HZ);  // TD = b11 (3)
  rtc.setCountdownTimerClockTicks(2);                                 // TIMER COUNTER 0/1                         
  rtc.enableHardwareInterrupt(TIMER_INTERRUPT);     // TIE = 1
  rtc.setCountdownTimerEnable(ENABLE);              // TE = 1

Also I change the name of the constant, from COUNTDOWN_TIMER_FREQUENCY_1/60_HZ to COUNTDOWN_TIMER_FREQUENCY_1_60_HZ.

I think we can close the issue.
It's ok?

**Comment by AndyEngland521** [comment]
Sounds good, thank you!

**Comment by glyndavidson** [comment]
@ionel-dragomirescu 
How did you get the interrupt to work, I can't seem to get it working.
Did you use something like "attachInterrupt(interuptPin, interruptHandler, CHANGE);" to handle the interrupt?

**Comment by ionel-dragomirescu** [comment]
Yes, I use attachInterrupt function.
  attachInterrupt(digitalPinToInterrupt(INT_PIN), interruptCount, RISING);
