### ISSUE TITLE
You should clear flags after disabling interrupts

### ISSUE THREAD

**Issue by glyndavidson** [sparkfun/SparkFun_RV-8803_Arduino_Library#7]
In the example files which show how to use interrupts, this line of code

`  rtc.disableAllInterrupts();`

Should really be immediately followed by 

`rtc.clearAllInterruptFlags(); `

Just in case an interrupt occurred whilst things were being disabled.

**Comment by AndyEngland521** [comment]
Hi @glyndavidson, I waffled for quite some time about whether or not to include this line as things were working in single examples and it almost seemed like overkill as the first call of your ISR should clear the flag anyway, however it seems some folks are having issues when moving between examples/copying the code into their own software. Fixed it in version v1.0.5
