### ISSUE TITLE
Alarm Interrupt weekday not working

### ISSUE THREAD

**Issue by cedricwritescode** [sparkfun/SparkFun_RV-8803_Arduino_Library#9]
I've tried to set an interrupt on a specific weekday. However it didn't work.

In the [Alarm_Interrupt example](https://github.com/sparkfun/SparkFun_RV-8803_Arduino_Library/blob/master/examples/Example4A-Alarm_Interrupt/Example4A-Alarm_Interrupt.ino) you should provide a number between 0 and 6
`uint8_t weekdayAlarmValue = 0; //0-6`

In the datasheet however the weekdays are specified each with one bit(bit 0=sunday; bit 6=saturday).
![rv-8803-setAlarmWeekday](https://user-images.githubusercontent.com/41518201/90330919-dccecd00-dfb0-11ea-9430-81985cf819e5.PNG)

Therefore the function setAlarmWeekday is incorrect.
It should look something like this, when you give it the correctly formated weekdays as a parameter:
```
bool RV8803::setAlarmWeekdays(uint8_t weekdays)
{
  uint8_t value = readRegister(RV8803_WEEKDAYS_DATE_ALARM);
  value &= (1 << ALARM_ENABLE); //clear everything but enable bit
  value |= 0x7F & weekdays
  return writeRegister(RV8803_WEEKDAYS_DATE_ALARM, value);
}
```

Then you would set it like this in the Alarm_Interrupt example:
```
#define SUNDAY 0x01
#define MONDAY 0x02
#define TUESDAY 0x04
#define WEDNESDAY 0x08
#define THURSDAY 0x10
#define FRIDAY 0x20
#define SATURDAY 0x40

...

uint8_t weekdayAlarmValue = SUNDAY | WEDNESDAY | SATURDAY; //set all weekdays with a | between them
 ```

**Comment by AndyEngland521** [comment]
Great catch @Redstoned  and great solution. I was meaning to shift a bit left by the argument (0-6) and it looks like that particular scrap of code got lost in the shuffle of things. However I think your solution is more elegant and I've implemented it in v1.1.0
